import { readFile, writeFile } from "node:fs/promises"

const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"))
await writeFile(
  new URL("../src/generated/version.ts", import.meta.url),
  `// Generated by tools/generate-version.mjs. Do not edit manually.\nexport const SYSTEM_VERSION = ${JSON.stringify(packageJson.version)}\n`,
)
